name: Dafny Formal Verification

on:
  push:
    paths:
      - 'verification/**'
      - '.github/workflows/dafny-verification.yml'
  pull_request:
    paths:
      - 'verification/**'
      - '.github/workflows/dafny-verification.yml'

jobs:
  dafny-verification:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install SwiftLint
        run: brew install dafny

      - name: Dafny verification
        run: time dafny verify verification/dfyconfig.toml --progress Batch
