---
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

name: Build
jobs:
  build:
    name: Build contract
    runs-on: runs-on=${{ github.run_id }}/family=c6a.8xlarge/image=ubuntu24-full-x64/extras=s3-cache
    container: rust:latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup RunsOn
        uses: runs-on/action@v2
        with:
          metrics: cpu,network,memory,disk,io
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libudev-dev
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Install dependencies
        run: cargo +stable install cargo-make cargo-near
      - name: Compile contract
        run: cargo make build

      - name: Generate launchpad types
        run: |
          chmod +x scripts/gen-launchpad-types.sh
          ./scripts/gen-launchpad-types.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts
          path: |
            res/aurora-launchpad-factory.wasm
            res/schema.ts

  publish:
    name: Publish contracts
    runs-on: runs-on=${{ github.run_id }}/family=c6a.large/image=ubuntu24-full-x64
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Publish contracts for ${{ github.ref }} release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: "contracts/*"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
